#Used for server port    
server:
  port: ${port:9411}
  
#Used for eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 13
    prefer-ip-address: true
spring:
  sleuth:
    enabled: false


#Using mysql as storage of zipkin
zipkin:
  storage:
    type: elasticsearch
    storage:
      elasticsearch:
        hosts: http://127.0.0.1:9200
        index: zipkin
        index-shards: 5
        index-replicas: 1 
    
   
#Used for application monitoring(actuator)    
management:
  security:
    enabled: false
#  context-path: /admin
  
endpoints:
  health:
    enabled: true
  shutdown:
    enabled: true
    
#logging:
#  config: 
#    classpath: "logback-spring.xml"
#  file:  ${spring.application.name}.log  